name: Food Ordering CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend-check:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install backend packages
        run: npm install

      - name: Build Docker image
        run: docker build -t food-ordering-backend .